name = input ("what is your name ")
print (f"Hello {name}")
fav_number = int(input ("what is your Favorite Number "))
print (f"Your Favorite number is {fav_number}")
print (f"Your Favorite number minus 10 is {fav_number - 10}")
